import styled, { keyframes } from 'styled-components';

export const textFocus = keyframes`
  0% {
    -webkit-filter: blur(5px);
    filter: blur(5px);
    opacity: 0.3;
  }
  100% {
    -webkit-filter: blur(0px);
    filter: blur(0px);
    opacity: default;
  }
`;

export const Main = styled.main`
  width: 100%;
  height: 500vh;
`;

export const Header = styled.header`
  position: fixed;
  top: 0;
  z-index: 999;
  width: 100%;
  padding: 1rem 5rem;
  background: var(--dark-grey);
  @media (max-width: 992px) {
    padding: 2%;
    overflow-x: auto;
  }
`;

export const HeaderContainer = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 3rem;
  max-width: 100rem;
  margin: 0 auto;
  @media (max-width: 992px) {
    max-width: 100%;
    margin: 0;
  }
`;

export const Logo = styled.div``;

export const LogoName = styled.span`
  font-size: 1.5rem;
  font-weight: 500;
`;

export const Nav = styled.nav`
  display: flex;
  align-items: center;
  position: sticky;
  position: -webkit-sticky;
  top: 0;
`;

export const List = styled.ul`
  display: flex;
  align-items: center;
  list-style: none;
`;

export const Item = styled.li`
  list-style: none;
  flex: 0 0 auto;
  margin-left: 1rem;
`;

export const Link = styled.a`
  font-size: 1rem;
  font-weight: 500;
  cursor: pointer;
`;

export const TextGreen = styled.span`
  color: var(--green);
`;

export const Section = styled.div`
  width: 100%;
  padding: 1rem 5rem;
  @media (max-width: 992px) {
    padding: 1rem 1.5rem;
  }
`;

export const Container = styled.div`
  display: flex;
`;

export const ContainerCenter = styled.div`
  display: flex;
  justify-content: start;
  @media (max-width: 992px) {
    justify-content: center;
  }
`;

export const ContainerFill = styled.div`
  display: flex;
  @media (max-width: 992px) {
    display: contents;
  }
`;

export const ContainerImage = styled.div`
  display: flex;
  @media (max-width: 992px) {
    display: none;
  }
`;

export const Text = styled.span`
  font-size: 1rem;
  font-weight: 500;
  animation: ${textFocus} 0.8s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
`;

export const TextLight = styled.span`
  color: var(--light-green);
  font-size: 1rem;
  font-weight: 700;
  animation: ${textFocus} 0.8s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
`;

/* ----------------------------------------------
 * Generated by Animista on 2021-7-23 7:6:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-flicker-in-glow
 * ----------------------------------------
 */
const textFlickerInGlow = keyframes`
0% {
    opacity: 0;
  }
  10% {
    opacity: 0;
    text-shadow: none;
  }
  10.1% {
    opacity: 1;
    text-shadow: none;
  }
  10.2% {
    opacity: 0;
    text-shadow: none;
  }
  20% {
    opacity: 0;
    text-shadow: none;
  }
  20.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.25);
  }
  20.6% {
    opacity: 0;
    text-shadow: none;
  }
  30% {
    opacity: 0;
    text-shadow: none;
  }
  30.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
  }
  30.5% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
  }
  30.6% {
    opacity: 0;
    text-shadow: none;
  }
  45% {
    opacity: 0;
    text-shadow: none;
  }
  45.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
  }
  50% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
  }
  55% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
  }
  55.1% {
    opacity: 0;
    text-shadow: none;
  }
  57% {
    opacity: 0;
    text-shadow: none;
  }
  57.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35);
  }
  60% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35);
  }
  60.1% {
    opacity: 0;
    text-shadow: none;
  }
  65% {
    opacity: 0;
    text-shadow: none;
  }
  65.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35), 0 0 60px rgba(255, 255, 255, 0.1);
  }
  75% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35), 0 0 60px rgba(255, 255, 255, 0.1);
  }
  75.1% {
    opacity: 0;
    text-shadow: none;
  }
  77% {
    opacity: 0;
    text-shadow: none;
  }
  77.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.4), 0 0 80px rgba(255, 255, 255, 0.2), 0 0 60px rgba(255, 255, 255, 0.1);
  }
  85% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.4), 0 0 80px rgba(255, 255, 255, 0.2), 0 0 60px rgba(255, 255, 255, 0.1);
  }
  85.1% {
    opacity: 0;
    text-shadow: none;
  }
  86% {
    opacity: 0;
    text-shadow: none;
  }
  86.1% {
    opacity: 1;
    text-shadow: 0 0 15px rgba(255, 255, 255, 0.6), 0 0 30px rgba(255, 255, 255, 0.45), 0 0 80px rgba(255, 255, 255, 0.25), 0 0 60px rgba(255, 255, 255, 0.1);
  }
  100% {
    opacity: 1;
    text-shadow: none;
  }
`;

export const LogoInfo = styled.span`
  color: var(--green);
  font-size: 1.5rem;
  font-weight: 700;
  animation: ${textFlickerInGlow} 4s linear both;
`;
