import { keyframes } from "styled-components";

/* ----------------------------------------------
 * Generated by Animista on 2021-7-23 7:6:54
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-flicker-in-glow
 * ----------------------------------------
 */

export const textFlickerInGlow = keyframes`
 0% {
     opacity: 0;
   }
   10% {
     opacity: 0;
     text-shadow: none;
   }
   10.1% {
     opacity: 1;
     text-shadow: none;
   }
   10.2% {
     opacity: 0;
     text-shadow: none;
   }
   20% {
     opacity: 0;
     text-shadow: none;
   }
   20.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.25);
   }
   20.6% {
     opacity: 0;
     text-shadow: none;
   }
   30% {
     opacity: 0;
     text-shadow: none;
   }
   30.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
   }
   30.5% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
   }
   30.6% {
     opacity: 0;
     text-shadow: none;
   }
   45% {
     opacity: 0;
     text-shadow: none;
   }
   45.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
   }
   50% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
   }
   55% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.45), 0 0 30px rgba(255, 255, 255, 0.25);
   }
   55.1% {
     opacity: 0;
     text-shadow: none;
   }
   57% {
     opacity: 0;
     text-shadow: none;
   }
   57.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35);
   }
   60% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35);
   }
   60.1% {
     opacity: 0;
     text-shadow: none;
   }
   65% {
     opacity: 0;
     text-shadow: none;
   }
   65.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35), 0 0 60px rgba(255, 255, 255, 0.1);
   }
   75% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.35), 0 0 60px rgba(255, 255, 255, 0.1);
   }
   75.1% {
     opacity: 0;
     text-shadow: none;
   }
   77% {
     opacity: 0;
     text-shadow: none;
   }
   77.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.4), 0 0 80px rgba(255, 255, 255, 0.2), 0 0 60px rgba(255, 255, 255, 0.1);
   }
   85% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.55), 0 0 30px rgba(255, 255, 255, 0.4), 0 0 80px rgba(255, 255, 255, 0.2), 0 0 60px rgba(255, 255, 255, 0.1);
   }
   85.1% {
     opacity: 0;
     text-shadow: none;
   }
   86% {
     opacity: 0;
     text-shadow: none;
   }
   86.1% {
     opacity: 1;
     text-shadow: 0 0 15px rgba(255, 255, 255, 0.6), 0 0 30px rgba(255, 255, 255, 0.45), 0 0 80px rgba(255, 255, 255, 0.25), 0 0 60px rgba(255, 255, 255, 0.1);
   }
   100% {
     opacity: 1;
     text-shadow: none;
   }
 `;

export const sliderKeyframes = keyframes`
 /* ----------------------------------------------
 * Generated by Animista on 2022-2-14 22:14:53
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation text-pop-up-top
 * ----------------------------------------
 */
  0% {
    -webkit-transform: translateY(0);
            transform: translateY(0);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: none;
  }
  100% {
    -webkit-transform: translateY(-25px);
            transform: translateY(-15px);
    -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
    text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
  }
`;
